theme:
  name: readthedocs
  analytics:
    gtag: G-P4NDRLGV8D

site_name: TobsDB Docs
repo_url: https://github.com/tobshub/tobsdb
edit_uri: blob/main/docs/
site_description: Official TobsDB documentation
site_author: TobsDB

nav:
  - Introduction: "index.md"
  - Getting Started: "getting-started.md"
  - Schema.tdb: "schema.md"
  - Clients:
      - Overview: "clients/overview.md"
      - JavaScript/Typescript: "clients/js.md"
